import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - the server build file is generated by Vite
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ build });
